CBES-82 Plugin: NoClassDefFoundError under Java 9
Motivation
==========
In Java 9, javax.xml.bind.DatatypeConverter is not on the class path
by default, and we get a NotClassDefFoundError.

Modifications
============
Use Guava's base64 decoder instead.

Result
======
Can decode base64 regardless of Java version.

(cherry-picked from commit 06744ed6fb043b755fb11cf9e5ed104021b4ad65)